window.PRODUCTS = [
  { code: "1", name: "MC DUR 1322 CA RAL 7032 A+B 30KG", unit: "KOM" },
  { code: "2", name: "MC DUR 1350 VK A+B 30KG", unit: "KOM" },
  { code: "3", name: "MC DUR 1200 RAL 9003 A+B 30KG", unit: "KOM" },
  { code: "4", name: "MC DUR 1200 GRAU A+B 30KG", unit: "KOM" },
  { code: "5", name: "MC DUR 1177 WV-A A+B 30KG", unit: "KOM" },
  { code: "6", name: "MC DUR 1177 WV-A A+B 10KG", unit: "KOM" },
  { code: "7", name: "MC DUR TOPSPEED RAL 7032 A+B 10KG", unit: "KOM" },
  { code: "8", name: "MC DUR TOPSPEED GRAU A+B 20KG", unit: "KOM" },
  { code: "9", name: "MC INJEKT POWERSEAL F 10L", unit: "KOM" },
  { code: "10", name: "MC VERDUENNUNG PU 10L", unit: "KOM" },
  { code: "11", name: "MC INJEKTIONSPACKER 150 KOM", unit: "PAK" },
  { code: "12", name: "NAFUFLEX EASY TECH 1 30L", unit: "KOM" },
  { code: "13", name: "MC WATERSTOP EXPANDS 20M", unit: "KOM" },
  { code: "14", name: "MC STELLMITTEL TX 19 1KG", unit: "KOM" },
  { code: "15", name: "MC FastTape 0.12x50m", unit: "kom" },
  { code: "16", name: "BD BUTYLBAND 10M", unit: "KOM" },
  { code: "17", name: "SB 78 0.12X50M", unit: "KOM" },
  { code: "18", name: "BOTAGREEN AE 10M", unit: "KOM" },
  { code: "19", name: "BOTAGREEN AE 30M", unit: "KOM" },
  { code: "20", name: "CENTRAMENT PROOF CP 10 18KG", unit: "KOM" },
  { code: "21", name: "CENTRAMENT PUMP PRIMER 0.2KG", unit: "KOM" },
  { code: "22", name: "D11 10L", unit: "KOM" },
  { code: "23", name: "MYCOFLEX 488 MS BETONGRAU 600ML", unit: "KOM" },
  { code: "24", name: "SEALING PLUG 22MM BLUE", unit: "KOM" },
  { code: "25", name: "SEALING UFO 22MM BLUE", unit: "KOM" },
  { code: "26", name: "EMCORIL COMPACT TOP 30KG", unit: "KOM" },
  { code: "27", name: "MC TOP B SIVI 25KG", unit: "KOM" },
  { code: "28", name: "KVARC 0.1-0.3mm 25kg", unit: "KOM" },
  { code: "29", name: "KVARC 0.4-0.8mm 25KG", unit: "KOM" },
  { code: "30", name: "GLASPERLEN 100-200 5kg", unit: "KOM" },
  { code: "31", name: "GLASPERLEN 200-300 5kg", unit: "KOM" },
  { code: "32", name: "EMCEKRETE SFM THIS 25KG", unit: "KOM" },
  { code: "33", name: "MC PROOF 530 LIQUID A+B 30.5kg", unit: "KOM" },
  { code: "34", name: "MC FAST ST 12KG", unit: "KOM" },
  { code: "35", name: "MC PROOF 501 FLEX A+B 30KG", unit: "KOM" },
  { code: "36", name: "ORTOLAN CLASSIC 711 30L", unit: "KOM" },
  { code: "37", name: "DF 9R GRAU 12kg", unit: "kom" },
  { code: "38", name: "MC FLEX PU 22 CONSTRUCT GRAU 600ml", unit: "KOM" },
  { code: "39", name: "OMBRAN ASP 25kg", unit: "KOM" },
  { code: "40", name: "DONNITIL RUST EX 10.5kg", unit: "KOM" },
  { code: "41", name: "DONNITIL OIL EX 10L", unit: "KOM" },
  { code: "42", name: "COLLUSAL SP GRAU A+B 5kg", unit: "KOM" },
  { code: "43", name: "MC COLOR FLAIR PURE RAL 7032 15L", unit: "KOM" },
  { code: "44", name: "BOTARED M49 25kg", unit: "KOM" },
  { code: "45", name: "PF 1 ROT 2.5L", unit: "KOM" },
  { code: "46", name: "PF 1 ANTHRAZIT 2.5L", unit: "KOM" },
  { code: "47", name: "PF GRAU 2.5L", unit: "KOM" },
  { code: "48", name: "MC DUR 1322 GRAU A+B 30KG", unit: "KOM" },
  { code: "49", name: "MC DUR 1200 RAL 7032 A+B 30kg", unit: "KOM" },
  { code: "50", name: "MC BETOSOLID SX A+B 2.5kg", unit: "KOM" },
  { code: "51", name: "MC BETOSOLID SX A+B 5kg", unit: "KOM" },
  { code: "52", name: "MC BETOSOLID SX A+B 10kg", unit: "KOM" },
  { code: "53", name: "OMBRAN MHP-SP 25kg", unit: "KOM" },
  { code: "54", name: "OMBRAN CPS A+B+C 22kg", unit: "KOM" },
  { code: "55", name: "CENTRAMENT RETARD 350 35kg", unit: "KOM" },
  { code: "56", name: "TRAKA ARMIRANA 48x50", unit: "KOM" },
  { code: "57", name: "TRAKA KREP 30X50", unit: "KOM" },
  { code: "58", name: "TRAKA KREP 48X50", unit: "KOM" },
  { code: "59", name: "TRAKA KREP AKRILNO LJEPILO 38X33", unit: "KOM" },
  { code: "60", name: "TRAKA KREP AKRILNO LJEPILO 48X33", unit: "KOM" },
  { code: "61", name: "MJESAC 100X10", unit: "KOM" },
  { code: "62", name: "MJESAC 120X10", unit: "KOM" },
  { code: "63", name: "PISTOLJ ZA SILIKON", unit: "KOM" },
  { code: "64", name: "KANTA 12L", unit: "KOM" },
  { code: "65", name: "KANTA 16L", unit: "KOM" },
  { code: "66", name: "KANTA 20L", unit: "KOM" },
  { code: "67", name: "METLA PVC BEZ DRSKE 50cm", unit: "KOM" },
  { code: "68", name: "MASKA ZA NOS I USTA", unit: "KOM" },
  { code: "69", name: "KOLJENICE 200x100x110", unit: "KOM" },
  { code: "70", name: "RUKAVICA NITRILNA XL", unit: "KOM" },
  { code: "71", name: "VALJAK VELUR 25cm", unit: "KOM" },
  { code: "72", name: "VALJAK VELUR 10CM", unit: "KOM" },
  { code: "73", name: "VALJAK ELITAKOLOR POLIAKRILNI 25cm", unit: "KOM" },
  { code: "74", name: "VALJAK HARDMAX 18 25cm", unit: "KOM" },
  { code: "75", name: "VALJAK HARDEX 18 25cm", unit: "KOM" },
  { code: "76", name: "VALJAK ELITAKOLOR 11 10cm", unit: "KOM" },
  { code: "77", name: "VALJAK HARDEX 11 10cm", unit: "KOM" },
  { code: "78", name: "VALJAK ZA UGLOVE AKRIL 9", unit: "KOM" },
  { code: "79", name: "VALJAK TRAKASTI POLIAMID 12cm", unit: "KOM" },
  { code: "80", name: "DRSKA ZA VALJAK 10cm", unit: "KOM" },
  { code: "81", name: "DRSKA ZA VALJAK 25cm", unit: "KOM" },
  { code: "82", name: "TELESKOP 0.8-1.4m", unit: "KOM" },
  { code: "83", name: "TELESKOP 1.1-1.8m", unit: "KOM" },
  { code: "84", name: "TELESKOP 1.6-3m", unit: "KOM" },
  { code: "85", name: "KADICA ZA FARBU PLASTICNA 30X16cm", unit: "KOM" },
  { code: "86", name: "KADICA ZA FARBU PLASTICNA 35X26cm", unit: "KOM" },
  { code: "87", name: "MREZICA MOLERSKA 30X22cm", unit: "KOM" },
  { code: "88", name: "MREZICA MOLERSKA 32X27cm", unit: "KOM" },
  { code: "89", name: "CETKICA 20mm", unit: "KOM" },
  { code: "90", name: "CETKICA 30mm", unit: "KOM" },
  { code: "91", name: "CETKICA 40mm", unit: "KOM" },
  { code: "92", name: "CETKICA 50mm", unit: "KOM" },
  { code: "93", name: "CETKICA 60mm", unit: "KOM" },
  { code: "94", name: "CETKICA 70mm", unit: "KOM" },
  { code: "95", name: "CETKICA 80mm", unit: "KOM" },
  { code: "96", name: "CETKICA UGAONA 2", unit: "KOM" },
  { code: "97", name: "CETKICA UGAONA 1.5", unit: "KOM" },
  { code: "98", name: "CETKA UGAONA 2.5", unit: "KOM" },
  { code: "99", name: "CETKA ZA FARBANJE PLAFONA 170X70mm", unit: "KOM" },
  { code: "100", name: "CETKA ZA KVASENJE 120mm", unit: "KOM" },
  { code: "101", name: "FOLIJA ZASTITNA 4x5m", unit: "KOM" },
  { code: "102", name: "VALJAK IGLICASTI 25cm", unit: "KOM" },
  { code: "103", name: "CIPELE SA KLINOVIMA", unit: "KOM" },
  { code: "104", name: "SPAKLA 2.5cm", unit: "KOM" },
  { code: "105", name: "SPAKLA 6cm", unit: "KOM" },
  { code: "106", name: "SPAKLA 8cm", unit: "KOM" },
  { code: "107", name: "SPAKLA 12cm", unit: "KOM" },
  { code: "108", name: "SPAKLA SA ODVIJACEM 15cm", unit: "KOM" },
  { code: "109", name: "SPAKLA ZA VELIKE POVRSINE 30cm", unit: "KOM" },
  { code: "110", name: "SPAKLA ZA VELIKE POVRSINE 50cm", unit: "KOM" },
  { code: "111", name: "SPAKLA ZA VELIKE POVRSINE 60cm", unit: "KOM" },
  { code: "112", name: "MISTRIJA 12x8cm", unit: "KOM" },
  { code: "113", name: "MISTRIJA 14x8cm", unit: "KOM" },
  { code: "114", name: "MISTRIJA 16x11cm", unit: "KOM" },
  { code: "115", name: "MISTRIJA 18x12cm", unit: "KOM" },
  { code: "116", name: "GLETARICA 28x12cm", unit: "KOM" },
  { code: "117", name: "CapaDIN 12.5L", unit: "KOM" },
  { code: "118", name: "CapaDIN 15L", unit: "KOM" },
  { code: "119", name: "CapaDIN 5L", unit: "KOM" },
  { code: "120", name: "Grundierkonzentrat 1L", unit: "KOM" },
  { code: "121", name: "CapaSOL LF Konzentrat 10L", unit: "KOM" },
  { code: "122", name: "HaftGrund 12.5L", unit: "KOM" },
  { code: "123", name: "HaftGrund 5L", unit: "KOM" },
  { code: "124", name: "Haftprimer 2.5L", unit: "KOM" },
  { code: "125", name: "Haftprimer 750ML", unit: "KOM" },
  { code: "126", name: "PU-SATIN 2.4L", unit: "KOM" },
  { code: "127", name: "PU-SATIN 700ML", unit: "KOM" },
  { code: "128", name: "PU-Gloss 2.4L", unit: "KOM" },
  { code: "129", name: "PU-Gloss 700ML", unit: "KOM" },
  { code: "130", name: "CapaTrend crna 12.5L", unit: "KOM" },
  { code: "131", name: "CapaMaXX 12.5L", unit: "KOM" },
  { code: "132", name: "SeidenLatex ELF 12.5L", unit: "KOM" },
  { code: "133", name: "SeidenLatex EKF 5L", unit: "KOM" },
  { code: "134", name: "Indeko-plus 12.5L", unit: "KOM" },
  { code: "135", name: "Diamonds Bronze 75G", unit: "KOM" },
  { code: "136", name: "Diamonds Gold 75g", unit: "KOM" },
  { code: "137", name: "CDUR DecorLasur KF Farblos 2.5L", unit: "KOM" },
  { code: "138", name: "CDUR WSF NQG 2.4L", unit: "KOM" },
  { code: "139", name: "KREATIVEFFEKT MIRROR 8kg", unit: "KOM" },
  { code: "140", name: "CapaTox 1L", unit: "KOM" },
  { code: "141", name: "Indeko W 2.5L", unit: "KOM" },
  { code: "142", name: "Dupa-inn 5L", unit: "KOM" },
  { code: "143", name: "Disbon 948 crni 2-4mm 1kg", unit: "KOM" },
  { code: "144", name: "Disbon 948 Bjeli 2-4mm 1kg", unit: "KOM" },
  { code: "145", name: "MC DUR TOPSPEED RAL 3009 A+B 10KG", unit: "KOM" },
  { code: "146", name: "MC DUR TOPSPEED RAL 5012 A+B 10KG", unit: "KOM" },
  { code: "147", name: "MS 6 BOTAMENT 310ml", unit: "kom" },
  { code: "148", name: "DF 9 R GRAU 5KG", unit: "KOM" },
  { code: "149", name: "USLUGA MATERIJALI I RUKE (INJEKTIRANJE)", unit: "m1" },
  { code: "999", name: "USLUGA UGRADNJE", unit: "M2" },
  { code: "1000", name: "INJEKTIRANJE (MATERIJAL I RUKE)", unit: "m1" },
  { code: "1001", name: "UGRADNJA HIDRO IZOLACIJE OMBRAN ASP", unit: "m2" },
];
